apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-admission-webhook
  labels:
    app: pod-admission-webhook
  namespace: admission-webhook-demo-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-admission-webhook
  template:
    metadata:
      labels:
        app: pod-admission-webhook
    spec:
      containers:
      - name: pod-admission-webhook
        image: registry.cn-beijing.aliyuncs.com/doc01/admission-webhook-demo:v5
        command:
          - "/admission-webhook-demo"
        args:
          - --metrics-address=127.0.0.1:8080
        ports:
          - containerPort: 9443
            name: webhook-server
            protocol: TCP
        volumeMounts:
          - mountPath: /tmp/k8s-webhook-server/serving-certs
            name: cert
            readOnly: true
        imagePullPolicy: IfNotPresent

        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 125m
            memory: 500Mi

      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: webhook-server-cert