apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: pod-admission-webhook
  annotations:
    cert-manager.io/inject-ca-from: $(CERTIFICATE_NAMESPACE)/$(CERTIFICATE_NAME)
webhooks:
  - name: pod-admission-webhook.kube-system.svc
    clientConfig:
      service:
        name: pod-admission-webhook
        namespace: kube-system
        path: "/mutate-pod"
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Fail
    namespaceSelector:
      matchLabels:
        pod-admission-webhook-injection: enabled
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]