apiVersion: v1
kind: Service
metadata:
  labels:
    app: pod-admission-webhook
  name: pod-admission-webhook
  namespace: admission-webhook-demo-system
spec:
  ports:
    - name: 443-9443
      port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    app: pod-admission-webhook
  type: ClusterIP
